name = "Django Editor"
description = "An application that uses PyScript"
packages = [
    "https://cdn.holoviz.org/panel/1.3.8/dist/wheels/bokeh-3.3.3-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.3.8/dist/wheels/panel-1.3.8-py3-none-any.whl",
    "numpy",
]


#packages = [
#    "https://cdn.holoviz.org/panel/1.4.5/dist/wheels/bokeh-3.4.2-py3-none-any.whl",
#    "https://cdn.holoviz.org/panel/1.4.5/dist/wheels/panel-1.4.5-py3-none-any.whl",
#    "numpy",
#]